services:
  druzhokbot:
    image: druzhokbot
    container_name: druzhokbot-container
    build:
      context: .
      dockerfile: druzhokbot/Dockerfile
    env_file:
      - .env
    restart: always
    network_mode: host
