//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DruzhokBot.Domain {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LogTemplates {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LogTemplates() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("DruzhokBot.Domain.LogTemplates", typeof(LogTemplates).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string NewUserJoinedChat {
            get {
                return ResourceManager.GetString("NewUserJoinedChat", resourceCulture);
            }
        }
        
        internal static string StartingDruzhokBot {
            get {
                return ResourceManager.GetString("StartingDruzhokBot", resourceCulture);
            }
        }
        
        internal static string StartListeningDruzhoBbot {
            get {
                return ResourceManager.GetString("StartListeningDruzhoBbot", resourceCulture);
            }
        }
        
        internal static string TryToKickUser {
            get {
                return ResourceManager.GetString("TryToKickUser", resourceCulture);
            }
        }
        
        internal static string VerificationFailed {
            get {
                return ResourceManager.GetString("VerificationFailed", resourceCulture);
            }
        }
        
        internal static string FinishingDruzhokBot {
            get {
                return ResourceManager.GetString("FinishingDruzhokBot", resourceCulture);
            }
        }
    }
}
