//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DruzhokBot.Domain {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TextResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TextResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DruzhokBot.Domain.TextResources", typeof(TextResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ласкаво просимо, {0}! Щоб група була захищена від ботів, пройдіть просту верифікацію. Натисніть на кнопку «🚫🤖» під цим повідомленням. Поспішіть, у вас є 90 секунд до автоматичного виліту з чату..
        /// </summary>
        internal static string NewUserVerificationMessage {
            get {
                return ResourceManager.GetString("NewUserVerificationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Robots will rule the world :).
        /// </summary>
        internal static string RandomUserClickedVerifyButtonResponse {
            get {
                return ResourceManager.GetString("RandomUserClickedVerifyButtonResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Привіт, я Дружок!
        ///
        ///Додай мене в свій чат, дай права адміна, і я перевірятиму щоб група була завжди захищена від спам-ботів..
        /// </summary>
        internal static string StartMessage {
            get {
                return ResourceManager.GetString("StartMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Верифікація не пройдена. Спробуйте пройти ще раз через 5 хвилин..
        /// </summary>
        internal static string VerificationFailed {
            get {
                return ResourceManager.GetString("VerificationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Верифікація пройдена. Ласкаво просимо!.
        /// </summary>
        internal static string VerificationSuccessfull {
            get {
                return ResourceManager.GetString("VerificationSuccessfull", resourceCulture);
            }
        }
    }
}
